-- Seed the Corduroy universal (core) metric library.
-- 36 library definitions (client_id = null, tier = 'core', benchmarkable = true)
-- from docs/scope-corekpis.md. Idempotent: upserts on the library-key partial
-- unique index (metric_key where client_id is null).
--
-- Unit vocabulary is mapped to the metric_definitions.unit enum:
--   dollars -> currency, units -> count, days -> days, ratio -> ratio.
-- widget_type/update_interval use sensible defaults (single_stat / monthly)
-- and can be tuned per metric in the admin Metric catalog.

insert into public.metric_definitions (
  metric_key, label, kind, tier, unit, category, stock_flow,
  formula_expression, description, widget_type, update_interval,
  benchmarkable, needs_review
) values
  -- Observed inputs (core) --------------------------------------------------
  ('total_revenue', 'Total Revenue', 'observed', 'core', 'currency', 'Financial', 'flow',
    null,
    'Sum of all sales income recognized in the period, before any costs. Include all P&L revenue lines; exclude loans, owner contributions, and asset sales.',
    'single_stat', 'monthly', true, false),
  ('total_cogs', 'Total COGS', 'observed', 'core', 'currency', 'Financial', 'flow',
    null,
    'Direct cost of producing or delivering what was sold in the period (materials, direct labor, inbound freight). Excludes overhead.',
    'single_stat', 'monthly', true, false),
  ('total_operating_expenses', 'Total Operating Expenses', 'observed', 'core', 'currency', 'Financial', 'flow',
    null,
    'Overhead incurred in the period (SG&A, rent, salaries, marketing, etc.). Excludes COGS, depreciation, interest, and taxes.',
    'single_stat', 'monthly', true, false),
  ('total_depreciation', 'Total Depreciation', 'observed', 'core', 'currency', 'Financial', 'flow',
    null,
    'Depreciation and amortization expense recognized in the period.',
    'single_stat', 'monthly', true, false),
  ('total_interest', 'Total Interest', 'observed', 'core', 'currency', 'Financial', 'flow',
    null,
    'Interest expense on debt in the period.',
    'single_stat', 'monthly', true, false),
  ('total_taxes', 'Total Taxes', 'observed', 'core', 'currency', 'Financial', 'flow',
    null,
    'Income or business taxes attributable to the period.',
    'single_stat', 'monthly', true, false),
  ('marketing_spend', 'Marketing Spend', 'observed', 'core', 'currency', 'Financial', 'flow',
    null,
    'Spend on customer acquisition in the period (ads, campaigns, agency). A subset of Operating Expenses, tracked separately for CAC.',
    'single_stat', 'monthly', true, false),
  ('total_member_revenue', 'Total Member Revenue', 'observed', 'core', 'currency', 'Membership', 'flow',
    null,
    'Revenue from memberships or subscriptions in the period. A subset of Total Revenue.',
    'single_stat', 'monthly', true, false),
  ('cash', 'Cash', 'observed', 'core', 'currency', 'Financial', 'stock',
    null,
    'Cash and cash equivalents on hand at the observation date.',
    'single_stat', 'monthly', true, false),
  ('accounts_receivable_dollars', 'Accounts Receivable (dollars)', 'observed', 'core', 'currency', 'Financial', 'stock',
    null,
    'Total outstanding customer invoices unpaid at the observation date.',
    'single_stat', 'monthly', true, false),
  ('accounts_receivable_count', 'Accounts Receivable (count)', 'observed', 'core', 'count', 'Financial', 'stock',
    null,
    'Count of open or unpaid invoices (or customer accounts) at the observation date.',
    'single_stat', 'monthly', true, false),
  ('active_customers', 'Active Customers', 'observed', 'core', 'count', 'Customers', 'stock',
    null,
    'Distinct customers considered active at the observation date, per the client''s active definition.',
    'single_stat', 'monthly', true, false),
  ('new_customers_acquired', 'New Customers Acquired', 'observed', 'core', 'count', 'Customers', 'flow',
    null,
    'Count of customers acquired for the first time during the period. Required to derive churn and CAC.',
    'single_stat', 'monthly', true, false),
  ('headcount', 'Headcount', 'observed', 'core', 'count', 'People', 'stock',
    null,
    'Number of employees at the observation date (define FTE vs. headcount convention per client).',
    'single_stat', 'monthly', true, false),
  ('b2b_leads', 'B2B Leads', 'observed', 'core', 'count', 'B2B Pipeline', 'flow',
    null,
    'New leads entering the funnel in the period.',
    'single_stat', 'monthly', true, false),
  ('b2b_prospects', 'B2B Prospects', 'observed', 'core', 'count', 'B2B Pipeline', 'flow',
    null,
    'Leads qualified into prospects in the period.',
    'single_stat', 'monthly', true, false),
  ('b2b_won', 'B2B Won', 'observed', 'core', 'count', 'B2B Pipeline', 'flow',
    null,
    'Deals closed-won in the period.',
    'single_stat', 'monthly', true, false),
  ('b2b_lost', 'B2B Lost', 'observed', 'core', 'count', 'B2B Pipeline', 'flow',
    null,
    'Deals closed-lost in the period.',
    'single_stat', 'monthly', true, false),
  ('members_total', 'Members Total', 'observed', 'core', 'count', 'Membership', 'stock',
    null,
    'Total active members at the observation date.',
    'single_stat', 'monthly', true, false),
  ('paid_in_full_members', 'Paid in Full Members', 'observed', 'core', 'count', 'Membership', 'stock',
    null,
    'Members on a paid-in-full plan at the observation date.',
    'single_stat', 'monthly', true, false),
  ('paid_in_full_renewals', 'Paid in Full Renewals', 'observed', 'core', 'count', 'Membership', 'flow',
    null,
    'Paid-in-full memberships renewed in the period.',
    'single_stat', 'monthly', true, false),

  -- Derived metrics ---------------------------------------------------------
  ('net_new_customers', 'Net New Customers', 'derived', 'core', 'count', 'Customers', null,
    'active_customers(end) - active_customers(baseline)',
    'Change in active customer count over the period versus the baseline.',
    'single_stat', 'monthly', true, false),
  ('net_new_revenue', 'Net New Revenue', 'derived', 'core', 'currency', 'Financial', null,
    'total_revenue(period) - total_revenue(baseline)',
    'Change in revenue over the period versus the baseline.',
    'single_stat', 'monthly', true, false),
  ('lost_customers', 'Lost Customers', 'derived', 'core', 'count', 'Customers', null,
    'new_customers_acquired - net_new_customers',
    'Customers lost during the period, derived once New Customers Acquired is observed.',
    'single_stat', 'monthly', true, false),
  ('annualized_revenue', 'Annualized Revenue', 'derived', 'core', 'currency', 'Financial', null,
    'total_revenue(period) * periods_per_year',
    'Period revenue scaled to a full year (e.g. monthly revenue x 12).',
    'single_stat', 'monthly', true, false),
  ('average_member_revenue', 'Average Member Revenue', 'derived', 'core', 'currency', 'Membership', null,
    'total_member_revenue / members_total',
    'Average revenue per member for the period.',
    'single_stat', 'monthly', true, false),
  ('b2b_marketing_cost_per_lead', 'B2B Marketing Cost per Lead', 'derived', 'core', 'currency', 'B2B Pipeline', null,
    'marketing_spend / b2b_leads',
    'Average marketing cost to generate one lead.',
    'single_stat', 'monthly', true, false),
  ('customer_acquisition_cost', 'Customer Acquisition Cost (CAC)', 'derived', 'core', 'currency', 'Customers', null,
    'marketing_spend / new_customers_acquired',
    'Average marketing cost to acquire one new customer. Uses gross customers acquired, not net.',
    'single_stat', 'monthly', true, false),
  ('days_sales_outstanding', 'Days Sales Outstanding (DSO)', 'derived', 'core', 'days', 'Financial', null,
    '(accounts_receivable_dollars / total_revenue) * days_in_period',
    'Average number of days to collect receivables.',
    'single_stat', 'monthly', true, false),

  -- Ratios / P&L roll-ups ---------------------------------------------------
  ('gross_profit', 'Gross Profit', 'ratio', 'core', 'currency', 'Financial', null,
    'total_revenue - total_cogs',
    'Revenue remaining after direct costs.',
    'single_stat', 'monthly', true, false),
  ('gross_margin', 'Gross Margin', 'ratio', 'core', 'ratio', 'Financial', null,
    '(total_revenue - total_cogs) / total_revenue',
    'Share of revenue kept after direct costs.',
    'single_stat', 'monthly', true, false),
  ('ebitda', 'EBITDA', 'ratio', 'core', 'currency', 'Financial', null,
    'total_revenue - total_cogs - total_operating_expenses',
    'Earnings before interest, taxes, depreciation, and amortization.',
    'single_stat', 'monthly', true, false),
  ('net_income', 'Net Income / Net Profit', 'ratio', 'core', 'currency', 'Financial', null,
    'total_revenue - total_cogs - total_operating_expenses - total_depreciation - total_interest - total_taxes',
    'True bottom-line profit for the period.',
    'single_stat', 'monthly', true, false),
  ('net_margin', 'Net Margin', 'ratio', 'core', 'ratio', 'Financial', null,
    'net_income / total_revenue',
    'Share of revenue kept as net profit.',
    'single_stat', 'monthly', true, false),
  ('revenue_per_employee', 'Revenue per Employee', 'ratio', 'core', 'currency', 'People', null,
    'total_revenue / headcount',
    'Revenue produced per employee.',
    'single_stat', 'monthly', true, false),
  ('churn_rate', 'Churn Rate', 'ratio', 'core', 'ratio', 'Customers', null,
    'lost_customers / active_customers(baseline)',
    'Share of starting customers lost during the period.',
    'single_stat', 'monthly', true, false)
on conflict (metric_key) where (client_id is null) do update set
  label = excluded.label,
  kind = excluded.kind,
  tier = excluded.tier,
  unit = excluded.unit,
  category = excluded.category,
  stock_flow = excluded.stock_flow,
  formula_expression = excluded.formula_expression,
  description = excluded.description,
  widget_type = excluded.widget_type,
  update_interval = excluded.update_interval,
  benchmarkable = excluded.benchmarkable,
  needs_review = excluded.needs_review;
