export {
  faArrowDown,
  faArrowUp,
  faBuilding,
  faChartPie,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faCloudArrowUp,
  faDiagramProject,
  faDownload,
  faFile,
  faFileCsv,
  faFileExcel,
  faFileLines,
  faFilePdf,
  faListCheck,
  faPen,
  faPlus,
  faShield,
  faTags,
  faTrash,
  faUserTie,
} from "@fortawesome/free-solid-svg-icons";
