export const PLACEHOLDER_ORG = "All-American Fitness";

export const vaultSources = [
  {
    section: "Financial",
    items: [
      {
        title: "QuickBooks transactions",
        meta: "Updated Mar 24, 2026",
        tag: "QB live",
        tagClass: "tag-green",
        done: true,
        icon: "💻",
      },
      {
        title: "P&L summary 2023–2025",
        meta: "Uploaded Mar 18, 2026",
        tag: "XLSX",
        tagClass: "tag-green",
        done: true,
        icon: "📄",
      },
      {
        title: "2025 tax return",
        meta: "Requested — awaiting upload",
        tag: "PDF",
        tagClass: "tag-muted",
        done: false,
        icon: "📄",
      },
    ],
  },
  {
    section: "Pipeline & sales",
    items: [
      {
        title: "Quotient quotes (938)",
        meta: "Updated Mar 19, 2026",
        tag: "Quotient API",
        tagClass: "tag-purple",
        done: true,
        icon: "📊",
      },
      {
        title: "Pipedrive CRM",
        meta: "Updated Mar 20, 2026",
        tag: "PD live",
        tagClass: "tag-red",
        done: true,
        icon: "👤",
      },
      {
        title: "AnswerConnect call logs",
        meta: "Updated Mar 19, 2026",
        tag: "API",
        tagClass: "tag-purple",
        done: true,
        icon: "📞",
      },
    ],
  },
  {
    section: "Operations & context",
    items: [
      {
        title: "Kickoff notes & SOW",
        meta: "Uploaded Mar 14, 2026",
        tag: "DOCX",
        tagClass: "tag-blue",
        done: true,
        icon: "📋",
      },
      {
        title: "elevatedconcrete.com",
        meta: "Scraped Mar 15, 2026",
        tag: "Web scrape",
        tagClass: "tag-green",
        done: true,
        icon: "🌐",
      },
      {
        title: "Crew & equipment schedule",
        meta: "Uploaded Mar 17, 2026",
        tag: "XLSX",
        tagClass: "tag-green",
        done: true,
        icon: "📄",
      },
      {
        title: "Subcontractor agreements",
        meta: "Requested — awaiting upload",
        tag: "PDF",
        tagClass: "tag-muted",
        done: false,
        icon: "🏠",
      },
    ],
  },
] as const;

export const planWeeks = [
  { week: 1, label: "Week 1", range: "Mar 31 – Apr 4", progress: 100, status: "complete" },
  { week: 2, label: "Week 2", range: "Apr 7–11", progress: 100, status: "complete" },
  { week: 3, label: "Week 3", range: "Apr 14–18", progress: 60, status: "active" },
  { week: 4, label: "Week 4", range: "Apr 21–25", progress: 0, status: "upcoming" },
  { week: 5, label: "Week 5", range: "Apr 28 – May 2", progress: 0, status: "upcoming" },
] as const;

export const planThemes = [
  { color: "theme-red", title: "Pipeline activation", sub: "Recover $75K–$100K" },
  { color: "theme-blue", title: "GC relationships", sub: "Add 3 new partners" },
  { color: "theme-green", title: "Interior slab growth", sub: "5+ quotes/month" },
  { color: "theme-purple", title: "Pipeline systems", sub: "Zero 90-day-old quotes" },
] as const;

export const staffClients = [
  {
    id: "aaf",
    initials: "AAF",
    name: "All-American Fitness",
    orgName: "All-American Fitness",
    location: "Austin, TX",
    dateCreated: "2026-05-16",
    engagementSubtitle: "Week 4 of 13 · Jun 22–28, 2026",
    meta: "Week 4 of 13 · on track",
    kpisOnTrack: 4,
    kpisAtRisk: 1,
    reviewLabel: "Review due Fri",
    attention: false,
  },
  {
    id: "ecs",
    initials: "ECS",
    name: "Elevated Concrete",
    orgName: "Elevated Concrete Solutions",
    location: "Austin, TX",
    dateCreated: "2026-01-08",
    engagementSubtitle: "Week 3 of 13 · Apr 14–18, 2026",
    meta: "Week 3 of 13 · 1 at risk",
    kpisOnTrack: 5,
    kpisAtRisk: 1,
    reviewLabel: "Review due Fri",
    attention: true,
  },
  {
    id: "rpg",
    initials: "RPG",
    name: "Riverside Plumbing",
    orgName: "Riverside Plumbing Group",
    location: "San Antonio, TX",
    dateCreated: "2025-11-14",
    engagementSubtitle: "Week 7 of 13 · Apr 14–18, 2026",
    meta: "Week 7 of 13 · review due",
    kpisOnTrack: 4,
    kpisAtRisk: 2,
    reviewLabel: "Review due Fri",
    attention: true,
  },
  {
    id: "mbg",
    initials: "MBG",
    name: "Metro Bakery Group",
    orgName: "Metro Bakery Group",
    location: "Dallas, TX",
    dateCreated: "2025-08-22",
    engagementSubtitle: "Week 11 of 13 · Apr 14–18, 2026",
    meta: "Week 11 of 13 · strong",
    kpisOnTrack: 6,
    kpisAtRisk: 0,
    reviewLabel: null,
    attention: false,
  },
  {
    id: "tas",
    initials: "TAS",
    name: "Tanner Auto Supply",
    orgName: "Tanner Auto Supply Co.",
    location: "Houston, TX",
    dateCreated: "2026-03-01",
    engagementSubtitle: "Week 2 of 13 · Apr 14–18, 2026",
    meta: "Week 2 of 13 · setup",
    kpisOnTrack: 2,
    kpisAtRisk: 0,
    reviewLabel: "Onboarding",
    attention: false,
  },
  {
    id: "cfl",
    initials: "CFL",
    name: "Coastal Fleet Logistics",
    orgName: "Coastal Fleet Logistics",
    location: "Corpus Christi, TX",
    dateCreated: "2025-12-03",
    engagementSubtitle: "Week 5 of 13 · Apr 14–18, 2026",
    meta: "Week 5 of 13 · on track",
    kpisOnTrack: 5,
    kpisAtRisk: 0,
    reviewLabel: null,
    attention: false,
  },
  {
    id: "vhr",
    initials: "VHR",
    name: "Vega HR Solutions",
    orgName: "Vega HR Solutions",
    location: "Fort Worth, TX",
    dateCreated: "2025-10-17",
    engagementSubtitle: "Week 9 of 13 · Apr 14–18, 2026",
    meta: "Week 9 of 13 · on track",
    kpisOnTrack: 5,
    kpisAtRisk: 1,
    reviewLabel: null,
    attention: false,
  },
] as const;

export type StaffClientListItem = (typeof staffClients)[number];
